export const GET_FEEDS_SUCCESS = "GET_FEEDS_SUCCESS";
export const GET_FEEDS_LODING = "GET_FEEDS_LODING";
export const GET_FEEDS_ERROR = "GET_FEEDS_ERROR";
export const GET_FEEDS_LOGOUT = "GET_FEEDS_LOGOUT";